# Generated by Django 5.1.3 on 2025-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='name',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
